### ISSUE TITLE
CIS 120 Academic Integrity Violation

### ISSUE THREAD

**Issue by maxmcc** [carlosbros/chat-server#1]
Please remove this git repository (or make it private). The repository contains code associated with CIS 120 at the University of Pennsylvania and providing it in a publicly accessible repository is in violation of the academic integrity policy.

Thank you for your compliance.

**Comment by carlosbros** [comment]
Sorry about that, I did not know. I will delete it now

**Comment by maxmcc** [comment]
Thank you.
